models/user.py
from utils.db import db
from werkzeug.security import check_password_hash
from flask_login import UserMixin


class User(db.Model, UserMixin) :
    """
    diseño y creacion de la tabla donde iran la informacion
    de los usuarios  en la base de datos 
    """
    
    __tablename__='user'
    
    id_user = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100))
    borrow_days = db.Column(db.Integer)
    debt = db.Column(db.Float)
    email = db.Column(db.String(100))
    password = db.Column(db.String(100))
    def check_password(self, password):
        return check_password_hash(self.password, password)

    

routes/inventary.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, send_from_directory
from models.doc import docs
from utils.db import db
from werkzeug.utils import secure_filename
import os

inventary = Blueprint("inventary", __name__)
inventary.add_url_rule(
    "/imagen/<filename>", endpoint="get_img", build_only=True
)
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}
UPLOAD_DIRECTORY = 'file_img/'
@inventary.route('/inventary')
def index():
    document = docs.query.all()
   
    return render_template('index.html', document = document)

@inventary.route('/inventary/new_doc', methods=['POST'])
def add_contact():
    """
    funcion que recibe la data del formulario y la guarda en la DB
    
    """
    if request.method == 'POST':
        
        # receive data from the form
        name = request.form['doc_name']
        author = request.form['author']
        units = request.form['doc_units']
        value = request.form['doc_value']
        daily_value = request.form['d_value']
        doc_type = request.form['doc_type']
        dealer_name = request.form['dealer']
        imagen = request.files['u_imagen']
        extension = os.path.splitext(imagen.filename)[1].lower() #se comprueba el tipo de documento
        #save image in a file 
        if imagen:
            if extension not in ALLOWED_EXTENSIONS:
                flash('no se anexo imagen', 'error')
            
            imagen.save(os.path.join(
                UPLOAD_DIRECTORY,
                secure_filename(imagen.filename)
            ))
        # create a new Contact object
        new_doc = docs( name, author, units, doc_type, value, daily_value, dealer_name)
       
        # save the object into the database
        db.session.add(new_doc)
        db.session.commit()
        
        flash('Document added successfully!')

        return redirect(url_for("inventary.index"))



@inventary.route("/inventary/update/<string:id>", methods=[ "GET","POST"])
def update(id):

    """
     funcion que recibe la data del formulario y actualiza los datos de un docuemnto
    en la DB, teniendo en cuenta el parametro de la ID del documento
    """
    # get document by id_document
    document = docs.query.get(id)

    if request.method == "POST":
        docs.doc_name = request.form['doc_name']
        docs.author = request.form['author']
        docs.units = request.form['doc_units']
        docs.doc_value = request.form['doc_value']
        docs.daily_value = request.form['d_value']
        docs.doc_type = request.form['doc_type']
        docs.dealer_name = request.form['dealer']
        #imagen = request.form['u_imagen']


        db.session.commit()

        flash('Document updated successfully!')

        return redirect(url_for('inventary.index'))
    
    return render_template("update.html", document=document)

@inventary.route("/inventary/delete/<id>", methods=["GET"])
def delete(id):
    """ funcion para borrar un objeto documento, teniendo en cuenta el parametro de la ID del documento"""
    document = docs.query.get(id)
    db.session.delete(document)
    db.session.commit()

    flash('Document deleted successfully!')

    return redirect(url_for("inventary.index"))


@inventary.route('/imagen/<filename>')
def get_img(filename):
    return send_from_directory( filename=UPLOAD_DIRECTORY + filename)

templates/index.html
{% extends 'layout.html'%}


{% block content%}


<div class="row">
    <div class="p-3">
        <!--barra de busqueda-->
        {%include ('partials/_searchbar.html')%}
    </div>
    <div class="col-md-5 p-1 ">
        <!--MENSAJES POR ACCIONES-->
        {% include('partials/_message.html') %}
        <!--Formulario-->
        {% include('partials/_docform.html') %}
    </div>
    

    <!--Lista de documentos-->
    <div class="col-md-7 p-1">
        {% for document in document %}
        <div class="card mb-1 text-white bg-dark">
            <div class="card-body py-2 px-3">
                <div class="d-flex justify-content-between">
                    <h5 class="fw-bold text-uppercase">{{document.doc_name}}</h5>
                    <div>
                        <a href="{{url_for('inventary.update', id= document.id_)}}" 
                        class="btn bg-black btn-sm rounded-0 text-white">Update</a>
                        <a href="{{url_for('inventary.delete', id= document.id_)}}" class="btn btn-danger btn-sm rounded-0">Delete</a>
                    </div> 
                </div>
                <div>
                    
                    <img src="{{ url_for('inventary.get_img', filename=filename) }}"  class="rounded float-start" width="200" height="200"
                    alt="No se encontro ningun archivo de imagen">
                    <p class="card-text">Author: {{document.author}}</p>
                    <p class="card-text">Genero: {{document.doc_type}}</p>
                    <p class="card-text">Unidades: {{document.units}}</p>
                    <p class="card-text">Valor ud: $ {{document.doc_value}}</p>
                    <p class="card-text">Valor por día: $ {{document.daily_value}}</p>
                </div>
            </div>
        </div>
        {% endfor %}        
    </div>


</div>
{% endblock %}

    

    
   

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-Library</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{{url_for('static', filename= 'css/main.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>
<body>
    {% include('partials/_navbar.html') %}
    <div class="container p-2">
        {% block content %}
        {% endblock %}
    </div>
    
    
</body>
<footer class="bd-footer py-4 py-md-5 mt-5 bg-dark">
    {% include('partials/_footer.html') %}

</footer>
</html>

templates/pasarela.html
<!--SAMPLE en desarrollo-->
<script src="https://sdk.mercadopago.com/js/v2"></script>

<div class="cho-container"></div>
<script>
  const mp = new MercadoPago('TEST-2e2f449e-d4d1-403c-8a10-97849d912746', {
    locale: 'es-CO'
  });

  mp.checkout({
    preference: {
      id: 'YOUR_PREFERENCE_ID'
    },
    render: {
      container: '.cho-container',
      label: 'Pagar',
    }
  });
</script>

templates/update.html
{% extends 'layout.html'%}

{% block content%}

<!--plantilla del formulario para actualizar datos de los documentos-->
<div class="col-md-8 offset-md-2">
    <form action="{{url_for('inventary.update', id = document.id_)}}" method="POST"  class="card bg-black text-light">
        <div class="card-body pd-4">
            <div class="md-3">
                <label for="doc_name">Update Doc's name: </label>
                <input type = "text" name = "doc_name" placeholder = "Doc's name" value = "{{document.doc_name}}" class="form-control rounded-0 bg-dark border-0 text-white">
            </div>
            <div class="md-3">
                <label for="author">Update author: </label>
                <input type = "text" name = "author" placeholder = "Author" value = "{{document.author}}" class="form-control rounded-0 bg-dark border-0 text-white">
            </div>
            <div class="md-3">
                <label for="doc_type">Update doc's type</label>
                <input type = "text" name = "doc_type" placeholder = "Doc's type" value = "{{document.doc_type}}" class="form-control rounded-0 bg-dark border-0 text-white">
            </div>
            <div class="md-3">
                <label for="doc_units">Update doc's units</label>
                <input type = "number" min=0 name = "doc_units" placeholder = "Doc's units" value = "{{document.units}}" class="form-control rounded-0 bg-dark border-0 text-white">
            </div>
            <div class="md-3">
                <label for="doc_value">Update doc's value</label>
                <input type = "number" min=0 step=0.01 name = "doc_value" placeholder = "Doc's value" value = "{{document.doc_value}}" class="form-control rounded-0 bg-dark border-0 text-white">
            </div>
            <div class="mb-3">
                <label for="doc_value">Update Doc's daily value</label>
                <input type="number" min=0 step=0.01 name="d_value" placeholder="Doc's value" value = "{{document.daily_value}}" class="form-control rounded-0 bg-dark border-0 text-white">
            </div>
            <div class="mb-3">
                <label for="doc_value">Doc's dealer</label>
                <input type="text" name="dealer" placeholder="Doc's dealer" value = "{{document.dealer_name}}" class="form-control rounded-0 bg-dark border-0 text-white">
            </div>
            <br>
            <button class="btn btn-secondary">Update</button>
        </div>
    </form>
</div>
{%endblock%}

templates/user.html
{% extends 'layout.html'%}


{% block content%}


<div class="row">
    <div class="p-3">
        <!--barra de busqueda-->
        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
    </div>
    <!--Lista de documentos-->
    <div class="col-md-12 offset-md-0">
        {% for document in document %}
        <div class="card mb-1 text-white bg-dark">
            <div class="card-body py-2 px-3">
                <div class="d-flex justify-content-between">
                    <h5 class="fw-bold text-uppercase">{{document.doc_name}}</h5>
                    <div>
                        <a href="{{url_for('sell.index')}}" class="btn bg-black btn-sm rounded-0 text-white">Comprar</a>
                        <a href="{{url_for('sell.index')}}"class="btn btn-danger btn-sm rounded-0">Alquilar</a>
                    </div> 
                </div>
                <div>
                    <img src="" alt="">
                    <p class="card-text">Author: {{document.author}}</p>
                    <p class="card-text">Genero: {{document.doc_type}}</p>
                    <p class="card-text">Unidades: {{document.units}}</p>
                    <p class="card-text">$ {{document.doc_value}}</p>
                </div>
            </div>
        </div>
    {% endfor %}        
    </div>


</div>
{% endblock %}