models/user.py
from utils.db import db
from werkzeug.security import check_password_hash
from flask_login import UserMixin


class User(db.Model, UserMixin) :
    """
    diseño y creacion de la tabla donde iran la informacion
    de los usuarios  en la base de datos 
    """
    
    __tablename__='user'
    
    id_user = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100))
    borrow_days = db.Column(db.Integer)
    debt = db.Column(db.Float)
    email = db.Column(db.String(100))
    password = db.Column(db.String(100))
    def check_password(self, password):
        return check_password_hash(self.password, password)

    

routes/inventary.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, send_from_directory
from models.doc import docs
from utils.db import db
from werkzeug.utils import secure_filename
import os

inventary = Blueprint("inventary", __name__)
inventary.add_url_rule(
    "/imagen/<filename>", endpoint="get_img", build_only=True
)
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}
UPLOAD_DIRECTORY = 'file_img/'
@inventary.route('/inventary')
def index():
    document = docs.query.all()
   
    return render_template('index.html', document = document)

@inventary.route('/inventary/new_doc', methods=['POST'])
def add_contact():
    """
    funcion que recibe la data del formulario y la guarda en la DB
    
    """
    if request.method == 'POST':
        
        # receive data from the form
        name = request.form['doc_name']
        author = request.form['author']
        units = request.form['doc_units']
        value = request.form['doc_value']
        daily_value = request.form['d_value']
        doc_type = request.form['doc_type']
        dealer_name = request.form['dealer']
        imagen = request.files['u_imagen']
        extension = os.path.splitext(imagen.filename)[1].lower() #se comprueba el tipo de documento
        #save image in a file 
        if imagen:
            if extension not in ALLOWED_EXTENSIONS:
                flash('no se anexo imagen', 'error')
            
            imagen.save(os.path.join(
                UPLOAD_DIRECTORY,
                secure_filename(imagen.filename)
            ))
        # create a new Contact object
        new_doc = docs( name, author, units, doc_type, value, daily_value, dealer_name)
       
        # save the object into the database
        db.session.add(new_doc)
        db.session.commit()
        
        flash('Document added successfully!')

        return redirect(url_for("inventary.index"))



@inventary.route("/inventary/update/<string:id>", methods=[ "GET","POST"])
def update(id):

    """
     funcion que recibe la data del formulario y actualiza los datos de un docuemnto
    en la DB, teniendo en cuenta el parametro de la ID del documento
    """
    # get document by id_document
    document = docs.query.get(id)

    if request.method == "POST":
        docs.doc_name = request.form['doc_name']
        docs.author = request.form['author']
        docs.units = request.form['doc_units']
        docs.doc_value = request.form['doc_value']
        docs.daily_value = request.form['d_value']
        docs.doc_type = request.form['doc_type']
        docs.dealer_name = request.form['dealer']
        #imagen = request.form['u_imagen']


        db.session.commit()

        flash('Document updated successfully!')

        return redirect(url_for('inventary.index'))
    
    return render_template("update.html", document=document)

@inventary.route("/inventary/delete/<id>", methods=["GET"])
def delete(id):
    """ funcion para borrar un objeto documento, teniendo en cuenta el parametro de la ID del documento"""
    document = docs.query.get(id)
    db.session.delete(document)
    db.session.commit()

    flash('Document deleted successfully!')

    return redirect(url_for("inventary.index"))


@inventary.route('/imagen/<filename>')
def get_img(filename):
    return send_from_directory( filename=UPLOAD_DIRECTORY + filename)

routes/registro.py
from flask import Flask, render_template, request, redirect, url_for, session,Blueprint,flash
from models.user import User
from models.forms import RegisterForm
from utils.db import db
from app import login_manager
from werkzeug.security import generate_password_hash
from flask_login import login_user, current_user

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

users = Blueprint('users', __name__)

@users.route('/')
def inicio():
    return render_template('users/_home.html')
  
@users.route('/register', methods= ('GET', 'POST'))
def register():
    form = RegisterForm(meta ={'csrf': False})
    if form.validate_on_summit():
        if User.query.filter_by(username=form.username.data).first():
            flash('Usuario duplicado')
        else:
            users= User()
            users.username = form.username.data
            users.email = form.email.data
            users.password = generate_password_hash(form.password.data)
            db.session.add(users)
            db.session.commit()
            login_user(users, remember=True)
            return redirect(render_template('users/user.html'))
   
    
    if form.errors:
        flash('{{form.errors}}')
    return render_template('users/_sigin.html', form = form)
           

routes/sell.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.doc import docs
from models.user import User
from utils.db import db

sell = Blueprint("sell", __name__)
@sell.route('/home')
def homepage():
    document = docs.query.all()
    return render_template('users/user.html', document=document)


@sell.route("/buy/<string:id>", methods=[ "POST","GET"])
def buy(id):
    # get id by id_document
    document = docs.query.get(id)
    if request.method == "POST":
        """primero se comprueba que aun existan unidades"""
        units = request.form['doc_units']
        """se resta la unidad que fue comprada y se pide el numero de dias que tendra con
        el producto y de ello se deduce el valor a pagar"""
        docs.units = docs.units - units
        User.debt = User.debt + docs.doc_value
        db.session.commit()
        flash ('Compra exitosa')
        return redirect(url_for('sell.homepage'))
    return render_template("users/_buying.html", document = document)

@sell.route("/borrow/<string:id>", methods=[ "POST","GET"])
def borrow(id):
    # get id by id_document
    document = docs.query.get(id)
    User.debt=1 
    
    if request.method == "POST":
        """primero se comprueba que aun existan unidades"""
      
        """se resta la unidad que fue comprada y se pide el numero de dias que tendra con
            el producto y de ello se deduce el valor a pagar"""
        User.borrow_days = request.form['doc_units']
        docs.units = docs.units - 1
        User.debt = User.debt * docs.daily_value
        db.session.commit()

        return redirect(url_for('sell.homepage'))
        
    return render_template("users/_borrow.html", document=document)

templates/users/_borrow.html
{% extends 'layout.html'%}

{% block content%}
<div class="row">
    <div class="col-md-5 p-1 ">
        <form action="{{url_for('sell.borrow', id = document.id_)}}" method="POST" class="card bg-black text-light" enctype="multipart/form-data">
            <div class="card-body pg-4">
                <div class="mb-3">
                    <label for="doc_units">Borrow days :</label>
                    <input type="number" min=1 max=30 name="doc_units" placeholder="Borrow days" class="form-control rounded-0 bg-dark border-0 text-white">
                </div>
                <button class="btn btn-secondary">save</button>
            </div>
            
        </form>
    </div>

    <div class="col-md-7 p-1">
        <div class="card mb-1 text-white bg-dark">
            <div class="card-body py-2 px-3">
                <div class="d-flex justify-content-between">
                    <h5 class="fw-bold text-uppercase">{{document.doc_name}}</h5>
                </div>
                <div>
                <img src="{{ url_for('inventary.get_img', filename=filename) }}"  class="rounded float-start" width="200" height="200"
                alt="No se encontro ningun archivo de imagen">
                <p class="card-text">Author: {{document.author}}</p>
                <p class="card-text">Genero: {{document.doc_type}}</p>
                <p class="card-text">Unidades: {{document.units}}</p>
                <p class="card-text">Valor ud: $ {{document.doc_value}}</p>
                <p class="card-text">Valor por día: $ {{document.daily_value}}</p>
                </div>
            </div>
        </div>  
    </div>

</div>
{%endblock%}

templates/users/_buying.html
{% extends 'layout.html'%}

{% block content%}
<div class="row">
    <div class="col-md-5 p-1 ">
        <form action="{{url_for('sell.buy', id = document.id_)}}" method="POST" class="card bg-black text-light" enctype="multipart/form-data">
            <div class="card-body pg-4">
                <div class="mb-3">
                    <label for="doc_units">Units number:</label>
                    <input type="number" min=0 max={{document.units}} name="doc_units" placeholder="Units number" class="form-control rounded-0 bg-dark border-0 text-white">
                </div>
                <a href="/pasarela.html"><button class="btn btn-secondary">save</button></a>
                <a href="/pasarela.html">save</a>
            </div>
            
        </form>
    </div>

    <div class="col-md-7 p-1">
        <div class="card mb-1 text-white bg-dark">
            <div class="card-body py-2 px-3">
                <div class="d-flex justify-content-between">
                    <h5 class="fw-bold text-uppercase">{{document.doc_name}}</h5>
                </div>
                <div>
                <img src="{{ url_for('inventary.get_img', filename=filename) }}"  class="rounded float-start" width="200" height="200"
                alt="No se encontro ningun archivo de imagen">
                <p class="card-text">Author: {{document.author}}</p>
                <p class="card-text">Genero: {{document.doc_type}}</p>
                <p class="card-text">Unidades: {{document.units}}</p>
                <p class="card-text">Valor ud: $ {{document.doc_value}}</p>
                <p class="card-text">Valor por día: $ {{document.daily_value}}</p>
                </div>
            </div>
        </div>  
    </div>

</div>
{%endblock%}

templates/users/_home.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>E-Library</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- Favicons -->
    <meta name="theme-color" content="#712cf9">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-bg-dark">
    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">E-Library</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="#">login</a>
        <a class="nav-link fw-bold py-1 px-0" href="{{url_for('users.register')}}">sign-in</a>
      </nav>
    </div>
  </header>

  <main class="px-3">
    <h1>E-Library</h1>
    <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea illum quae, aspernatur repellat possimus nam aliquam culpa maxime voluptates ipsa libero ut impedit quas nihil nemo eveniet assumenda amet ad?</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white text-black">Learn more</a>
    </p>
  </main>

  <footer class="mt-auto text-white-50">
    <p>E-Library <a href="#" class="text-white">Terminos &amp Condiciones</a></p>
  </footer>
</div>


    
  </body>
</html>

templates/users/_login.html
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-Library</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link href="/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

        <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.2/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.2/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.2/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">
    <link rel="stylesheet" href="{{url_for('static', filename= 'css/log.css')}}">
    <!-- Custom styles for this template -->
    
    </head>
    <body class="text-center">
    
    <main class="form-signin w-100 m-auto">
        <form action="{{ url_for('registro.login') }}" method="POST">
            
            <h1 class="h3 mb-3 fw-normal">Please login</h1>
            
            <div class="form-floating">
                <input type="email" type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                <label for="floatingInput">Email address</label>
            </div>
            <div class="form-floating">
                <input name="password" type="password" class="form-control" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword">Password</label>
            </div>
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
            <p class="bottom">Don't have an account?  <a class="bottom" href="{{url_for('registro.register')}}"> Sign Up here</a></p>
          </div>
        </form>
    </main>


    
    </body>
</html>

templates/users/_sigin.html
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-Library</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
        <!-- Favicons -->
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{{url_for('static', filename= 'css/log.css')}}">
    {%include('users/css.html')%}
    </head>
    <body class="text-center">
        
    {%include('users/sigin/_sign_form.html')%}


    
    </body>
</html>

templates/users/css.html
<style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }
  </style>

templates/users/user.html
{% extends 'layout.html'%}


{% block content%}


<div class="row">
    <div class="p-3">
        <!--barra de busqueda-->
        {%include ('partials/_searchbar.html')%}
    </div>


    <!--Lista de documentos-->
    <div class="col-md-12 offset-md-0">
        {% for document in document %}
        <div class="card mb-1 text-white bg-dark">
            <div class="card-body py-2 px-3">
                <div class="d-flex justify-content-between">
                    <h5 class="fw-bold text-uppercase">{{document.doc_name}}</h5>
                    <div>
                        <a href="{{url_for('sell.buy',  id= document.id_)}}" class="btn bg-black btn-sm rounded-0 text-white">Comprar</a>
                        <a href="{{url_for('sell.borrow',  id= document.id_)}}"class="btn btn-danger btn-sm rounded-0">Alquilar</a>
                    </div> 
                </div>
                <div>
                    <img src="{{ url_for('inventary.get_img', filename=filename) }}" alt="No se encontro ningun archivo de imagen">
                    <p class="card-text">Author: {{document.author}}</p>
                    <p class="card-text">Genero: {{document.doc_type}}</p>
                    <p class="card-text">Unidades: {{document.units}}</p>
                    <p class="card-text">$ {{document.doc_value}}</p>
                </div>
            </div>
        </div>
    {% endfor %}        
    </div>


</div>
{% endblock %}